#!/bin/bash
chrootEnvPath=/opt/new-system-env
#if [[ `whoami` != "root" ]]; then
#    echo 请使用 root 权限运行
#    exit 1
#fi
echo aa > /tmp/env-$USER.txt
if [[ ! -f $chrootEnvPath/tmp/env-$USER.txt ]]; then
    echo 未挂载目录，立即挂载
    sudo gx-env-mount-root
fi
command="$@"
#echo $command
pkexec env DISPLAY=$DISPLAY chroot $chrootEnvPath "$@"
#echo $@