#!/bin/bash
chrootEnvPath=/opt/new-system-env
gx-env-run-root python3 /gx-env/gx-env-load-desktop-in-chroot
if [[ ! -d /usr/share/applications/gx-env ]]; then
    sudo mkdir /usr/share/applications/gx-env -p
fi
sudo cp $chrootEnvPath/gx-env/desktop/* /usr/share/applications/gx-env -v